version: "3.9"
services:
  postgres:
    image: postgres:14.5
    environment:
      POSTGRES_DB: "MARKOV_205"
      POSTGRES_USER: "MARKOV_205"
      POSTGRES_PASSWORD: "MARKOV_205"
      PGDATA: "/var/lib/postgresql/data/pgdata-1"
    volumes:
      - docker/db/scripts/first_db:/docker-entrypoint-initdb.d
      - dz:/var/lib/postgresql/data-1
    ports:
      - "5432:5432"