version: "3.9"
services:
  postgres-library:
    image: postgres:14.5
    environment:
      POSTGRES_DB: "MARKOV_205"
      POSTGRES_USER: "MARKOV_205"
      POSTGRES_PASSWORD: "MARKOV_205"
      PGDATA: "/var/lib/postgresql/data/pgdata-library"
    volumes:
      - ./docker/db/scripts/library:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  postgres-trains:
    image: postgres:14.5
    environment:
      POSTGRES_DB: "MARKOV_205"
      POSTGRES_USER: "MARKOV_205"
      POSTGRES_PASSWORD: "MARKOV_205"
      PGDATA: "/var/lib/postgresql/data/pgdata-trains-6"
    volumes:
      - ./docker/db/scripts/trains:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/postgresql/data
    ports:
      - "5436:5432"

  postgres-hospital:
    image: postgres:14.5
    environment:
      POSTGRES_DB: "MARKOV_205"
      POSTGRES_USER: "MARKOV_205"
      POSTGRES_PASSWORD: "MARKOV_205"
      PGDATA: "/var/lib/postgresql/data/pgdata-hospital"
    volumes:
      - ./docker/db/scripts/hospital:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/postgresql/data
    ports:
      - "5434:5432"